# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5a8053663f479139f1d142029473f3ba9ee18ca5754d7eac63266f4c92b2d38c7173b7b0736ab5b56ef79e1033dfee4a4f7f070ba1718b78cb47c66fff798c9

test:
  secret_key_base: d3c87687e59d80092f5f4ad7cec3bf7e767b9945ac5cdb938b548e4c9ec99d7e2579429dde12dc5eda7adbbc5cc3751378098dca4bb63d7a3da4d80c9c4ef0c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
